apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  labels:
    app: tasks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: tasks:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          resources:
            requests:
              memory: "128Mi"  # Solicitação de 128MiB de memória
              cpu: "250m"      # Solicitação de 250 milicores de CPU
            limits:
              memory: "256Mi"  # Limite de 256MiB de memória
              cpu: "500m"      # Limite de 500 milicores de CPU

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "128Mi"  # Solicitação de 128MiB de memória
              cpu: "250m"      # Solicitação de 250 milicores de CPU
            limits:
              memory: "256Mi"  # Limite de 256MiB de memória
              cpu: "500m"      # Limite de 500 milicores de CPU

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"  # Solicitação de 128MiB de memória
              cpu: "250m"      # Solicitação de 250 milicores de CPU
            limits:
              memory: "256Mi"  # Limite de 256MiB de memória
              cpu: "500m"      # Limite de 500 milicores de CPU